site_name: ZEIT.IO Dokumentation
site_url: https://docs.zeit.io/

nav:
  - common:
    - Start: 'index.md'
    - Start: 'index.en.md'
  - employee_context:
    - common: 'mitarbeiter/index.md'
    - common: 'mitarbeiter/index.en.md'
    - time_tracking: 'mitarbeiter/zeiterfassung.md'
    - time_tracking: 'mitarbeiter/zeiterfassung.en.md'
    - vacations: 'mitarbeiter/urlaube.md'
    - vacations: 'mitarbeiter/urlaube.en.md'
  - freelancer_context:
    - Start: 'freiberufler/index.md'
    - Start: 'freiberufler/index.en.md'
    - onboarding: 'freiberufler/onboarding.md'
    - onboarding: 'freiberufler/onboarding.en.md'
    - gutschriftverfahren: 'freiberufler/gutschriftverfahren.md'
    - gutschriftverfahren: 'freiberufler/gutschriftverfahren.en.md'
    - projects: 'freiberufler/projekte.md'
    - projects: 'freiberufler/projekte.en.md'
    - time_tracking: 'freiberufler/zeiterfassung.md'
    - time_tracking: 'freiberufler/zeiterfassung.en.md'
  - approver_context:
    - common: 'genehmiger/index.md'
    - common: 'genehmiger/index.en.md'
  - organisations_context:
    - common: 'organisationen/index.md'
    - common: 'organisationen/index.en.md'
    - approver: 'organisationen/genehmiger.md'
    - approver: 'organisationen/genehmiger.en.md'
    - empployee_contracts: 'organisationen/mitarbeiter_vertraege.md'
    - empployee_contracts: 'organisationen/mitarbeiter_vertraege.en.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2024 REIZ Solutions GmbH

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zeit-io/zeit-user-docs
      name: GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCStqDRc35lVJ_7Y2RLdBR3g/videos
      name: YouTube

theme:
  name: material
  language: de
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - i18n:
      languages:
        de: "Deutsch"
        en: "English"
      default_language: 'de'
      no_translation:
        en: "This page isn't translated to English."
        de: "Diese Seite ist nicht ins Deutsche übersetzt."
      translate_nav:
        de:
          common: "Allgemein"
          employee_context: "Mitarbeiter Kontext"
          freelancer_context: "Freiberufler Kontext"
          approver_context: "Genehmiger Kontext"
          organisations_context: "Organisations Kontext"
          page title: "ZEIT.IO Dokumentation"
          approver: "Genehmiger"
          onboarding: "Onboarding"
          gutschriftverfahren: "Gutschriftverfahren"
          projects: "Projekte"
          time_tracking: "Zeiterfassung"
          vacations: "Urlaube"
          empployee_contracts: "Mitarbeiterverträge"
        en:
          common: "Common"
          employee_context: "Employee context"
          freelancer_context: "Freelancer context"
          approver_context: "Approver context"
          organisations_context: "Organisations context"
          page title: "ZEIT.IO Documentation"
          approver: "Approver"
          onboarding: "Onboarding"
          gutschriftverfahren: "Credit note procedure"
          projects: "Projects"
          time_tracking: "Time tracking"
          vacations: "Vacations"
          empployee_contracts: "Employee contracts"
